### ISSUE TITLE
Invisible bullet points :0

### ISSUE THREAD

**Issue by codeswift27** [7368697661/Ultra-Lobster#10]
The bullet point's are there when I highlight them...
![Screen Shot 2022-11-12 at 5 37 58 pm](https://user-images.githubusercontent.com/70664378/201497300-724c639c-c185-46c7-95ec-a464dec7c05d.png)

But not otherwise
![Screen Shot 2022-11-12 at 5 38 04 pm](https://user-images.githubusercontent.com/70664378/201497299-99256b57-7fc9-4ab1-899b-5b01d0902500.png)

I tried digging through the code, but I'm still pretty new to css hehe. I hope you can look into this issue when/if you have the time :)

**Comment by breeeige** [comment]
Hello! Go into the Style Settings for Ultra Lobster. There should be a category called "Type Palettes". You'll find "Bullet Point" under that. Then, key in `'-'` into the text box. It should appear afterwards.
<img width="584" alt="image" src="https://user-images.githubusercontent.com/57622055/203523549-a8b88b2c-b3d0-4849-af64-0c8ca64d0796.png">

**Comment by codeswift27** [comment]
Oh, it works! I could've sworn I tried that before, but I guess not. Tysm!!
