### ISSUE TITLE
Fonts not applied

### ISSUE THREAD

**Issue by SuperTempAccount** [7368697661/Ultra-Lobster#12]
Hey,

Thanks for the generosity in making this theme. Could you let me know how to get the fonts shown in the previews?
![image](https://user-images.githubusercontent.com/83566267/208502714-f3730432-c506-4477-9783-c97e54351196.png)

Mine looks like this out of the box...
![image](https://user-images.githubusercontent.com/83566267/208503118-43a3c59a-6e32-4e0d-90b0-e7d173ffa8ef.png)

These are the font settings (nothing set)
![image](https://user-images.githubusercontent.com/83566267/208503041-6f64f98c-7c93-48df-a84a-afb8b7257bee.png)

Edit: I installed these fonts
![image](https://user-images.githubusercontent.com/83566267/208510119-c96a8965-5dc5-4a00-9ffa-35715f5e5862.png)

this is the result
![image](https://user-images.githubusercontent.com/83566267/208510038-93bdb4fa-642b-4fa2-bb82-002675818d07.png)

**Comment by 7368697661** [comment]
Hi! Thanks so much for trying the theme and writing all of this up :) i actually need to redo how fonts are handled, so if you don't mind hanging tight for another couple days, i'm hoping to get that figured out 💖

So, _with_ Style Settings, are the fonts still not setting correctly?

**Comment by maudlinmandrake** [comment]
I'm also having this problem. With Style Settings, the only font settings that will change are headers. Editor, interface, monospace and title fonts are not affected by any changes made.

**Comment by lukemt** [comment]
I did have a similar problem once. I don't quite know what was wrong, but uninstalling the theme and then reinstalling fixed it for me. Please try this and let us know if it helps!

**Comment by maudlinmandrake** [comment]
> I did have a similar problem once. I don't quite know what was wrong, but uninstalling the theme and then reinstalling fixed it for me. Please try this and let us know if it helps!

Tried this out and sadly it had no effect.

**Comment by lukemt** [comment]
Ok, then we have to wait for the font update I guess

**Comment by SuperTempAccount** [comment]
The latest update seems to have fixed the issue. I had to go through the style settings and hit reset on all of them. The results are now much better. Thanks @7368697661 :)
![image](https://user-images.githubusercontent.com/83566267/211214054-7024c5b7-806d-4aa8-9b79-34877dbaa2d7.png)
