### ISSUE TITLE
Tag formatting issue

### ISSUE THREAD

**Issue by Clivusistheseatofthesoul** [7368697661/Ultra-Lobster#17]
YOS NEW UPDATE

The tags (background + font) don't seem to format properly in reading view:
<img width="1138" alt="image" src="https://user-images.githubusercontent.com/75022258/211442431-fbf26d3f-6e18-4de1-a723-67a8eb6869c6.png">

<img width="981" alt="image" src="https://user-images.githubusercontent.com/75022258/211442516-383b7cb5-5f73-4072-b186-69d0af6f52aa.png">

Looking forward to font palettes!

**Comment by 7368697661** [comment]
Hi! i personally like minimal tags in reading mode, but i can see how that would have been confusing :) i went ahead and added a toggle in Style Settings for minimal tags! i also added a border to tags, but i'm not sold on it; let me know what you think.

**Comment by 7368697661** [comment]
Sorry I typed up a response and never hit send 🙈 I wanted to say that there should be a version live that splits the difference; rounder corners, thicc font, and no border :) if anyone wants the old background-less version, there should be a style settings toggle 💖

**Comment by Clivusistheseatofthesoul** [comment]
Looks fab!! dig the new tags :))
