### ISSUE TITLE
Callout font size

### ISSUE THREAD

**Issue by Clivusistheseatofthesoul** [7368697661/Ultra-Lobster#18]
Hi,

Not sure if this is a feature but callout titles with H1 sized font look abit... _wonky_ and cramped, could we have an option to reduce the size of the font? tyyyy

<img width="1362" alt="image" src="https://user-images.githubusercontent.com/75022258/211948870-f1b5748c-fe3e-4e2f-9b54-f9df1df08740.png">

**Comment by 7368697661** [comment]
I just did another pass and changed how that value is calculated, it should be a bit better now. Let me know if that works for you  :)

**Comment by Clivusistheseatofthesoul** [comment]
Look great! :))
