### ISSUE TITLE
Floating pill in the navigation back arrow 

### ISSUE THREAD

**Issue by MatheusZarkov** [7368697661/Ultra-Lobster#19]
In the upper left corner where the navigation arrows are, this "pill" is always showing, not for the first time for me and does not go away at all. 

![2023-01-19 01_56_26-Personal Tasks - THE MAIN ONE - Obsidian v1 1 9](https://user-images.githubusercontent.com/69830959/213358870-1ae710f4-cf57-46ad-9171-cd0fa1620abb.png)

I did a CTRL Shift i to look what was causing that and this is what appeared:

![](https://i.imgur.com/zt8wrTg.png)

**Comment by 7368697661** [comment]
Hey sorry this took so long; i completely rebuilt the button styles so this should be fixed. Super weird that was showing up, it was a hold over from one of my other themes but should be gone now.
