### ISSUE TITLE
Kanban button text hard to read + menubar icon glitch

### ISSUE THREAD

**Issue by Clivusistheseatofthesoul** [7368697661/Ultra-Lobster#3]
The world rejoiced when Kneecaps said "its lobster'in time" then proceeded to lobster everywhere. Actual peak theme, 10/10 would reinstall with extra lobsters.

OK real feedback now, its hard to see the buttons on Kanban because they're the standard shade of grey 

<img width="1121" alt="image" src="https://user-images.githubusercontent.com/75022258/197367868-fb844632-7716-4603-931b-0ee6d4da072c.png">

**Comment by 7368697661** [comment]
Uh oh, what's going on here?? 
![image](https://user-images.githubusercontent.com/87339163/197618469-ac90cc1c-60b5-4e30-a778-433ee99481db.png)

**Comment by Clivusistheseatofthesoul** [comment]
Yeah I was going to mention that! Only glitches out when in windowed mode on Mac. This is what it looks like expanded (1) and collapsed (2). Looks normal fullscreen (3)

<img width="1440" alt="expanded" src="https://user-images.githubusercontent.com/75022258/197674497-7afe13e1-dbb5-4d77-a031-707b7a1e49f3.png">

<img width="1440" alt="collapsed" src="https://user-images.githubusercontent.com/75022258/197674568-d3dac7b7-50b6-4fe9-9dc1-1b4b90fb5f4e.png">

<img width="1440" alt="fullscreen" src="https://user-images.githubusercontent.com/75022258/197674625-d46353c8-b77b-4ced-941e-54b44ab8979c.png">

**Comment by Clivusistheseatofthesoul** [comment]
> Awh you are too sweet! I am so glad you are enjoying the theme 🥰 I went ahead and made some small tweaks to the contrast, but it's certainly difficult to balance user accents --how would you feel about removing the accent color from the buttons?

Wouldn't mind removing colours for Kansan buttons! Whatever you feel fits :)

**Comment by 7368697661** [comment]
Also, sorry, I haven't forgotten this; I'm still looking into it (slowly, and I pushed a sort-of fix...) --I don't have a Mac so I had no idea there was an issue there >~< Also, let me know if those Kanbans look better! I think it should be more minimal, now?

**Comment by Clivusistheseatofthesoul** [comment]
> Also, sorry, I haven't forgotten this; I'm still looking into it (slowly, and I pushed a sort-of fix...) --I don't have a Mac so I had no idea there was an issue there >~< Also, let me know if those Kanbans look better! I think it should be more minimal, now?

Dig it. Button text looks much more visible now! The dashed table borders does take some getting used to, as the vertical border thickness is different from the horizontal border thickness, not sure if thats a bug or intentional

<img width="722" alt="image" src="https://user-images.githubusercontent.com/75022258/199609466-3909b167-7146-4c79-a1f4-3ae2c51ec906.png">
 

Anyways, **Twiddling thumbs** eagerly awaiting your next update and style settings (and any obviously any cheekily-crustaceous, carcinisation-related eastereggs)

**Comment by Clivusistheseatofthesoul** [comment]
noted the Menubar was fixed:

<img width="717" alt="image" src="https://user-images.githubusercontent.com/75022258/211946710-c8f52bb4-05ce-4fb9-b668-748d78227b68.png">

<img width="618" alt="image" src="https://user-images.githubusercontent.com/75022258/211946784-f6ab7ace-40a8-44b6-a465-900ba7ab40ba.png">

Tables also look clean:

<img width="793" alt="image" src="https://user-images.githubusercontent.com/75022258/211947204-e6155f39-e225-4ff0-9a8c-b203117136f0.png">
