### ISSUE TITLE
Scrambled text after installing Ultra lobster

### ISSUE THREAD

**Issue by danieltomasz** [7368697661/Ultra-Lobster#5]
I am on Obsidian 1.0.3 with vault with many plugins
After installing and enabling Ultra Lobster the text of the Obsidian menu is scrambled
<img width="1620" alt="image" src="https://user-images.githubusercontent.com/7980381/198539755-0014055d-6fb3-43b0-a786-d079c397b170.png">

I am not able to reproduce this in the Obsidian Sandbox, I will investigate the situation

**Comment by 7368697661** [comment]
Hi! I was just wondering if this issue is still happening. Did you say it was or was not working in a blank vault without any plugins?

**Comment by danieltomasz** [comment]
it is solved when I tried installing it now, it was happening only in my vault, not in the Sanboxed one
