### ISSUE TITLE
Would love to see LYT Mode in the Color Palettes

### ISSUE THREAD

**Issue by nickmilo** [7368697661/Ultra-Lobster#7]
First, bravo for a beautiful and joyful theme. When you have more time, I'd love to work with you to get a color palette option of LYT Mode in your theme. (https://github.com/nickmilo/LYT-Mode) Feel free to reach out

**Comment by lukemt** [comment]
Nick Milo!!!!!

Ok, I will volenteer and create a pull request and then you guys can have a look and review.

**Comment by nickmilo** [comment]
Oh wow, cool! Only if you have time ofc, and no worries if things get busy, totally understand

**Comment by 7368697661** [comment]
Sorry everyone! I've been super busy haha. By all means, feel free to submit any color scheme! I would also be beyond honored to get this going 🥰 I am so glad you enjoy the theme, that means quite a bit!

Here is my first rather rushed stab at a LYT, let me know what the palette is and I (or someone idk haha, I'm _super_ excited to see what @lukemt lukemt comes up with) can toss them into this:

```
.theme-dark.ul-lyt-dt {
  --ul-pink: 239, 212, 191;
  --ul-red: 230, 57, 70;
  --ul-peach: 255, 205, 178;
  --ul-yellow: 242, 204, 143;
  --ul-green: 96, 153, 62;
  --ul-sky: 114, 161, 229;
  --ul-blue: 82, 178, 207;
  --ul-lavender: 144, 151, 192;
  --ul-text: 185, 195, 223;
  --ul-subtext0: 160, 167, 187;
  --ul-overlay2: 124, 132, 156;
  --ul-overlay1: 0,255,0;
  --ul-overlay0: 0,0,255;
  --ul-surface2: 108, 113, 132;
  --ul-surface1: 0, 0, 0, 0.035;
  --ul-surface0: 52, 58, 75;
  --ul-base: 45, 48, 57;
  --ul-shell: 30, 31, 36;
  --ul-stalk: 52, 58, 75;
}
```
(_i know my colors are a mess, i need to redo my variables so badly ;-;_)

![image](https://user-images.githubusercontent.com/87339163/199171445-38d6fa57-fa81-4b4a-a161-e5480660d84c.png)

**Comment by nickmilo** [comment]
Cool! Here are most of the LYT Mode colors you'll likely need: 

LYT MODE COLORS –––––––––––––––––––––

    --h1-color: var(--color-yellow-900); d9d617
    --h2-color: var(--color-purple-700); b894ff
    --h3-color: var(--color-cyan-540); 39b5db
    --h4-color: var(--color-green-700); 72d5a5
    --h5-color: var(--color-slate-500); b9c3df
    --h6-color: var(--color-slate-700); 9fa7bc
    --background-primary: var(--color-gray-90); 2d3039
    --background-primary-alt: var(--color-gray-100); 23242a
    --text-normal:  72c3d5
    --link-color: var(--color-magenta-700);  ff80b7

**Comment by lukemt** [comment]
Oh, wow that's it! 
Just combined those and this is what it looks like, pretty lyt!

<img width="1441" alt="grafik" src="https://user-images.githubusercontent.com/3893274/199294891-72f62116-92db-4d81-9d0a-b16757eed4e4.png">

**Comment by nickmilo** [comment]
So cool, I want to play! Should I add that css code to the bottom of the Ultra Lobster css? Or are you planning to push these changes?

**Comment by 7368697661** [comment]
Amazing work, @lukemt 🥳I'm going to push a new update with this included, now! (In the future I definitely want to add most of these color variables to style settings, as well!) ty so much for such a wonderful colorscheme @nickmilo 🥰
